In [1]:
import numpy as np

In [2]:
a11=np.array([[1,2],[5,6]])
b11=np.array([[1,2],[12,9]])
b12=np.array([[3],[5]]).reshape((2,1))
b21=np.array([10,11]).reshape((1,2))
a12=np.array([[3],[7]])
a21=np.array([[9,12],[10,11]])
a22=np.array([[13],[12]])
b22=np.array([12]).reshape((1,1))
a=np.dot(a11,b11)
b=np.dot(a12,b21)
print(a+b)
c=np.dot(a11,b12)
d=np.dot(a12,b22)
print(c+d)
e=np.dot(a21,b11)
f=np.dot(a22,b21)
print(e+f)
g=np.dot(a21,b12)
h=np.dot(a22,b22)
print(g+h)

[[ 55  53]
 [147 141]]
[[ 49]
 [129]]
[[283 269]
 [262 251]]
[[243]
 [229]]


In [3]:
z=np.concatenate((a+b,c+d),axis=1)
z1=np.concatenate((e+f,g+h),axis=1)
x=np.concatenate((z,z1))
print(x)

[[ 55  53  49]
 [147 141 129]
 [283 269 243]
 [262 251 229]]
